include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - unawaited_futures

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.freezed.dart"
